#Pressure correction so that it will match pressure on sealevel. 
#Correction in Pa
#If Correction is 0 then it is stored what is received from RuuviTag
#Some idea can be taken from here: https://www.mide.com/air-pressure-at-altitude-calculator
Pressure:
  Correction: 1300

#Location of InfluxDB
Database:
  ConnectionString: http://localhost:8086
  
  #
  # InfluxDB 2.X
  #
  # Change these to match your DB configuration
  #
  Org: Org-name
  #Token needs to have write permission to bucket
  Token: Users_token
  Bucket: weather

  #
  #InfluxDB 1.8
  #
  ####
  #### Comment all rows under InfluxDB 2.x if you are using InfluxDB 1.8 ####
  ####
  #
  #If database does not have authetication keep Token commented
  #Otherwise uncomment next row and provide username and password to use for authetication
  #Token: <username>:<password>
  #
  #Bucket has database name to store measurements, uncomment for InfluxDB1,8
  #Bucket: weather

#Storing interval in seconds
#Default is store next measurement after 15s send by the same RuuviTag sensors
#Set to 0 to store all measurements
Measurements:
  StoreDelay: 15

#
#Data
#

#Common tag for all Ruuvitag sensors
Address: "YourAddress"

#List of Ruuvitag sensors to be stored to DB
#If sensor is not on the list it won't be stored to DB
#MAC addresses are without leading zeros!
Sensors: 
    - "aa:1e:7b:f3:yy:1"
    - "bb:e3:18:33:yy:xx"
    - "cc:5a:86:8d:yy:xx"

#Location tag for each Ruuvitag
#Both MAC and Location tag can be used to separate each Ruuvitag sensors in DB

"aa:e3:18:33:yy:1":
  Location: "Outside"
  
"bb:1e:7b:f3:yy:xx":
  Location: "Sauna"

"cc:5a:86:8d:yy:xx":
  Location: "Inside"
