#Pressure correction so that it will match pressure on sealevel. 
#Correction in Pa
#If Correction is 0 then it is stored what is received from RuuviTag
#Some idea can be taken from here: https://www.mide.com/air-pressure-at-altitude-calculator
Pressure:
  Correction: 1300

#Location of QuestDB
#Change username and password
#Change password keyword to "token" if you use token based authentication
Database:
  ConnectionString: "http::addr=localhost:9000;username=User;password=Password;"
 
#Storing interval in seconds
#Default is store next measurement after 15s send by the same RuuviTag sensors
#Set to 0 to store all measurements
Measurements:
  StoreDelay: 15

#
#Data
#

#Common tag for all Ruuvitag sensors
#Useful if you move and want to see measurements from one address
Address: "StreetAddress"

#List of Ruuvitag sensors to be stored to DB
#If sensor is not on the list it won't be stored to DB
#MAC addresses are without leading zeros!
Sensors: 
    - "aa:1e:7b:f3:yy:xx"
    - "bb:e3:18:33:yy:xx"
    - "cc:5a:86:8d:yy:xx"

#Location tag for each Ruuvitag
#Both MAC and Location tag can be used to separate each Ruuvitag sensors in DB

"aa:1e:7b:f3:yy:xx":
  Location: "Balcony"
  
"bb:e3:18:33:yy:xx":
  Location: "Sauna"

"cc:5a:86:8d:yy:xx":
  Location: "Livingroom"
