name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure environment
      run: make env
      
    - name: Run tests
      run: make test
      
    - name: Do build
      run: make build
